#!/bin/bash

# FireFetch Dashboard - Appwrite Setup Script
# This script helps configure Appwrite integration for the dashboard

set -e

echo "==================================================================="
echo "FireFetch Dashboard - Appwrite Integration Setup"
echo "==================================================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if Appwrite is running
echo "Checking Appwrite availability..."
if curl -s http://localhost:8090/v1/health > /dev/null 2>&1; then
    echo -e "${GREEN}✓ Appwrite is running${NC}"
else
    echo -e "${RED}✗ Appwrite is not accessible at http://localhost:8090${NC}"
    echo "Please start Appwrite first:"
    echo "  cd /home/ubuntu/ai/backend"
    echo "  docker compose up -d"
    exit 1
fi

echo ""
echo "==================================================================="
echo "Configuration Setup"
echo "==================================================================="
echo ""

# Check if .env.local already exists
if [ -f .env.local ]; then
    echo -e "${YELLOW}⚠ .env.local already exists${NC}"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env.local"
        exit 0
    fi
fi

# Prompt for configuration
echo "Please provide the following information:"
echo "(Press Enter to use default values shown in brackets)"
echo ""

read -p "Appwrite Endpoint [http://localhost:8090/v1]: " ENDPOINT
ENDPOINT=${ENDPOINT:-http://localhost:8090/v1}

read -p "Project ID [firefetch-dashboard]: " PROJECT_ID
PROJECT_ID=${PROJECT_ID:-firefetch-dashboard}

read -p "Database ID [dashboard]: " DATABASE_ID
DATABASE_ID=${DATABASE_ID:-dashboard}

read -p "Settings Collection ID [settings]: " SETTINGS_ID
SETTINGS_ID=${SETTINGS_ID:-settings}

read -p "Metrics History Collection ID [metrics_history]: " METRICS_ID
METRICS_ID=${METRICS_ID:-metrics_history}

read -p "Incidents Collection ID [incidents]: " INCIDENTS_ID
INCIDENTS_ID=${INCIDENTS_ID:-incidents}

read -p "Alerts Collection ID [alerts]: " ALERTS_ID
ALERTS_ID=${ALERTS_ID:-alerts}

echo ""
echo "Creating .env.local file..."

cat > .env.local << EOF
# Appwrite Backend Configuration
# Generated by setup-appwrite.sh on $(date)

# Appwrite Endpoint
NEXT_PUBLIC_APPWRITE_ENDPOINT=$ENDPOINT

# Appwrite Project ID
NEXT_PUBLIC_APPWRITE_PROJECT_ID=$PROJECT_ID

# Database ID
NEXT_PUBLIC_APPWRITE_DATABASE_ID=$DATABASE_ID

# Collection IDs
NEXT_PUBLIC_APPWRITE_COLLECTION_SETTINGS=$SETTINGS_ID
NEXT_PUBLIC_APPWRITE_COLLECTION_METRICS=$METRICS_ID
NEXT_PUBLIC_APPWRITE_COLLECTION_INCIDENTS=$INCIDENTS_ID
NEXT_PUBLIC_APPWRITE_COLLECTION_ALERTS=$ALERTS_ID
EOF

echo -e "${GREEN}✓ .env.local created successfully${NC}"
echo ""

# Check if appwrite package is installed
echo "Checking dependencies..."
if ! grep -q '"appwrite"' package.json; then
    echo -e "${YELLOW}⚠ Appwrite SDK not found in package.json${NC}"
    read -p "Install Appwrite SDK? (Y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        echo "Installing Appwrite SDK..."
        npm install appwrite
        echo -e "${GREEN}✓ Appwrite SDK installed${NC}"
    fi
else
    echo -e "${GREEN}✓ Appwrite SDK already installed${NC}"
fi

echo ""
echo "==================================================================="
echo "Next Steps"
echo "==================================================================="
echo ""
echo "1. Open Appwrite Console:"
echo "   ${YELLOW}http://localhost:8090${NC}"
echo ""
echo "2. Create/verify the following in Appwrite:"
echo "   - Project: ${YELLOW}$PROJECT_ID${NC}"
echo "   - Database: ${YELLOW}$DATABASE_ID${NC}"
echo "   - Collections: ${YELLOW}$SETTINGS_ID, $METRICS_ID, $INCIDENTS_ID, $ALERTS_ID${NC}"
echo ""
echo "3. See detailed setup instructions:"
echo "   ${YELLOW}cat APPWRITE_SETUP.md${NC}"
echo ""
echo "4. Restart the dashboard:"
echo "   ${YELLOW}npm run dev${NC}  (development)"
echo "   ${YELLOW}docker compose restart${NC}  (production)"
echo ""
echo -e "${GREEN}Setup complete!${NC}"
echo ""
